apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kbot
  namespace: default
spec:
  interval: 1m0s
  chart:
    spec:
      chart: kbot
      version: "0.2.0"
      sourceRef:
        kind: HelmRepository
        name: kbot-oci
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/itopsandrii/kbot
      tag: v1.1.1-24a859b-linux-amd64
