apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kbot-oci
  namespace: flux-system
spec:
  interval: 1m0s
  type: oci
  url: oci://ghcr.io/itopsandrii
  secretRef:
    name: ghcr-login

