apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pet-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: pet-repo
    namespace: flux-system
  targetNamespace: default
