name: kbot CI/CD

on:
  push:
    branches: [main, develop]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/itopsandrii/kbot:${{ github.sha }}

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm chart
        run: helm package ./helm

      - name: Push Helm chart to GHCR
        run: helm push ./kbot-*.tgz oci://ghcr.io/itopsandrii/kbot
